services:
  - type: web
    name: backend
    env: node
    region: frankfurt # or "oregon" if closer
    branch: main
    buildCommand: 'npm install && npm run build'
    startCommand: 'npm run start:prod'
    envVars:
      - key: PORT
        value: 10000
